#Configuration file for BungeeCordPE


#BungeeCordPE listen port, What port will BungeeCordPE listens on?
Port:

# Forcing a default server will force any players connecting through the ip to always join a server like Hub ..ect)
# Max players is the max of players that can be on all servers at once. The host is the ip bungeecordpe will listen on. 



query_port: 19132
Force_Default: false
Default_server: Hub
max_players: 500
fallback_server: Hub
host: localhost
  
#To add a new server, Just use the following example format
#Example:
# IP:
# Port:
#
Servers:
   Hub:
     IP: test.example.com
       Port: 19133
       motd: "A BungeeCordPE Server"
       

...