#  ____                               _____              _ _____  ______ 
# |  _ \                             / ____|            | |  __ \|  ____|
#| |_) |_   _ _ __   __ _  ___  ___| |     ___  _ __ __| | |__) | |__   
# |  _ <| | | | '_ \ / _` |/ _ \/ _ \ |    / _ \| '__/ _` |  ___/|  __|  
# | |_) | |_| | | | | (_| |  __/  __/ |___| (_) | | | (_| | |    | |____ 
# |____/ \__,_|_| |_|\__, |\___|\___|\_____\___/|_|  \__,_|_|    |______|
#                     __/ |                                              
#                    |___/                                               
# BungeeCordPE Config!
#

#BungeeCordPE listen port, What port will BungeeCordPE listens on?
Port:

# Forcing a default server will force any players connecting through the ip to always join a server like Hub ..ect)
# Max players is the max of players that can be on all servers at once. The host is the ip bungeecordpe will listen on. 



ListenPort: 19132
ForceDefault: false
Defaultserver: Hub
max_players: 500
fallbackserver: Hub
Host: localhost
  
#To add a new server, Just use the following example format
#Example:
# IP:
# Port:
#
...
