#BouncyBall config file.
#RemoteServer and RemoteServer port are for the main server all users connect to.

#Remote Server information:
remoteServer: localhost
remoteServerPort: 19133

#Logging information.
logDecodeErrors: true
logChat: true